### ISSUE TITLE
Method of determining the next project in queue?

### ISSUE THREAD

**Issue by hyperobject** [scratchdesignstudio/quick-link#1]
How should we determine the next project in the queue?

**Comment by hyperobject** [comment]
I suppose we could always look through comments until we find a project link that an SDS curator has replied to.

**Comment by TheGrits** [comment]
I'm thinking a script that checks the following: (Bottom up)
1) Does comment have link?
2) SDS curator replied? (We could use username specifics here to verify it is indeed an SDS curator replying)

**Comment by TheGrits** [comment]
Hmm, you're onto something with the last comment with a reply. That would be more efficient, but sometimes we might look over a comment or two, so ideally we'd like to catch the accidental look-overs.

**Comment by hyperobject** [comment]
On the /site-api/comments/gallery/xxxxxxxx page, we can look for curator replies by finding all elements that match ".top-level-reply > .replies > .reply > .comment". We can get the parent comment by finding the data-thread attribute on the .replies element.

**Comment by TheGrits** [comment]
Is there a way we can see the comment author with the site API?

**Comment by hyperobject** [comment]
Yeah - the inner HTML of elements that match ".comment > .info > .name > a" is the name of the user. Once we detect a comment that we want, we can get the comment author's username pretty easily.

**Comment by TheGrits** [comment]
We might have some trouble... https://scratch.mit.edu/studios/1788915/comments/#comments-18163451 
Basically, we probably need to search the comments for the key word "added" as well, as sometimes we reply to a comment out of queue.

**Comment by hyperobject** [comment]
Well, looking for 'added' in the comment shouldn't be a problem.

**Comment by hyperobject** [comment]
@TheGrits I've fleshed out comment detection pretty fully. You can try it out on the live site by using getLastComment(commentpage) in the console. It returns false if the page has been fully checked (with some bugs, unfortunately), and the next unreplied comment ID if it hasn't. The code's a bit messy, but I've tried to document the important bits.

**Comment by hyperobject** [comment]
OK, looks like comment detection and link changing works now. I'll close the issue, but feel free to reopen it if you think something needs to be changed

**Comment by TheGrits** [comment]
Awesome work, I'm amazed!
