### ISSUE TITLE
Synchronous HTTP request causing issues with crossorigin.me

### ISSUE THREAD

**Issue by TheGrits** [scratchdesignstudio/quick-link#10]
![screenshot 2017-01-24 at 7 36 28 pm](https://cloud.githubusercontent.com/assets/12952370/22273098/776ef4d4-e26c-11e6-97d6-cb59f40cef25.png)

**Comment by hyperobject** [comment]
The origin bit isn't the issue here - that only shows up if you navigate to that URL in your browser (because reasons :/). The real problem (I *think*) is the synchronous XMLHttpRequest stuff. I'll try and migrate to async or figure out a different way to do synchronous requests.
