### ISSUE TITLE
Auto-update studio

### ISSUE THREAD

**Issue by hyperobject** [scratchdesignstudio/quick-link#2]
@TheGrits I was browsing through the scratch-www code, and I noticed that if we want to, we could automatically get the number of comments on the current SDS by getting JSON from http://api.scratch.mit.edu/proxy/featured and getting the SDS studio id. Do you think that would be worth possibly lengthening load times of the site?

**Comment by TheGrits** [comment]
I'm not sure how much this would help, unless I'm understanding you incorrectly. Does this just return the total number of comments in the studio, or the comments themselves?

**Comment by hyperobject** [comment]
Sorry, I think I described that terribly. :P
The thing I'm suggesting would fetch the current SDS studio ID so we
wouldn't have to manually update it every time we launch a new studio.

**Comment by TheGrits** [comment]
Ohh! Now it make sense! That's actually a great idea!

**Comment by hyperobject** [comment]
Cool, I've implemented it. Let me know if you notice anything weird happening.
